-- ═══════════════════════════════════════════════════════════════════════════
-- Contas a Pagar — Biomassa Chaparini — estrutura do banco no Supabase
--
-- Rodar no SQL Editor do projeto (pode rodar de novo sem perder dados).
--
-- Segurança:
--  • Quem não está logado não vê nada (RLS em todas as tabelas).
--  • Usuário logado, ativo e com perfil só LÊ as tabelas diretamente.
--  • Toda gravação passa por uma função que confere o perfil (mesma matriz de
--    permissões do sistema) — ninguém grava direto nas tabelas.
--  • Lançamentos trazem uma "chave de envio": se o mesmo envio chegar duas vezes
--    (clique duplo, conexão que caiu), o segundo não cria registro novo.
-- ═══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────── TABELAS ───────────────────────────────────

-- Perfil de cada login (a senha fica no Supabase Auth, nunca aqui)
create table if not exists public.usuarios (
  id         uuid primary key references auth.users (id) on delete cascade,
  email      text not null,
  nome       text not null default '',
  login      text unique,               -- nome curto gravado nas contas (ex.: nathaliabrito)
  perfil     text check (perfil in ('ADMIN', 'DIRETOR', 'FINANCEIRO')),
  ativo      boolean not null default false,  -- novo login só entra depois que um ADMIN ativar
  criado_em  timestamptz not null default now()
);

create table if not exists public.fornecedores (
  id               bigint generated by default as identity primary key,
  nome             text not null,
  tipo             text not null,
  documento        text not null default '',
  telefone         text not null default '',
  email            text not null default '',
  categoria_padrao text not null default '',
  observacao       text not null default '',
  ativo            boolean not null default true
);

create table if not exists public.categorias (
  id         bigint generated by default as identity primary key,
  nome       text not null,
  tipo       text not null,
  frota      boolean not null default false,
  observacao text not null default '',
  ativo      boolean not null default true
);

create table if not exists public.solicitantes (
  id           bigint generated by default as identity primary key,
  nome         text not null,
  departamento text not null default '',
  cargo        text not null default '',
  email        text not null default '',
  telefone     text not null default '',
  ativo        boolean not null default true
);

create table if not exists public.contas (
  id              bigint generated by default as identity primary key,
  fornecedor      text not null,
  categoria       text not null,
  solicitante     text not null default '',
  descricao       text not null,
  valor           numeric(14, 2) not null check (valor >= 0),
  vencimento      date not null,
  competencia     text not null default '',          -- 'AAAA-MM'
  data_pagamento  date,
  forma_pagamento text not null default '',
  juros_multa     numeric(14, 2) not null default 0,
  num_documento   text not null default '',
  observacao      text not null default '',
  usuario         text not null default '',          -- login de quem lançou
  data_registro   date not null default (now() at time zone 'America/Sao_Paulo')::date,
  chave_envio     text unique,                       -- evita lançamento em dobro
  criado_em       timestamptz not null default now()
);

create index if not exists contas_vencimento_idx on public.contas (vencimento);

-- ─────────────────────── PERFIL DE QUEM ESTÁ LOGADO ────────────────────────

-- Perfil do usuário logado, só se estiver ativo (null = sem acesso)
create or replace function public.meu_perfil() returns text
language sql stable security definer set search_path = public as $$
  select perfil from public.usuarios where id = auth.uid() and ativo
$$;

-- Login curto do usuário logado (gravado em contas.usuario)
create or replace function public.meu_login() returns text
language sql stable security definer set search_path = public as $$
  select coalesce(nullif(login, ''), email) from public.usuarios where id = auth.uid()
$$;

-- Dados do próprio usuário (usado logo após o login)
create or replace function public.meu_usuario() returns json
language sql stable security definer set search_path = public as $$
  select json_build_object('id', id::text, 'nome', nome, 'email', email,
                           'login', coalesce(nullif(login, ''), email), 'perfil', perfil, 'ativo', ativo)
  from public.usuarios where id = auth.uid()
$$;

-- ─────────────────────────── FUNÇÕES AUXILIARES ────────────────────────────

create or replace function public._exigir_perfil(permitidos text[]) returns text
language plpgsql stable security definer set search_path = public as $$
declare
  p text := public.meu_perfil();
begin
  if p is null then
    raise exception 'Sessão expirada ou usuário inativo. Faça login novamente.' using errcode = '42501';
  end if;
  if not (p = any (permitidos)) then
    raise exception 'Seu perfil (%) não tem permissão para esta ação.', p using errcode = '42501';
  end if;
  return p;
end $$;

create or replace function public._obrigatorio(p jsonb, campos text[]) returns void
language plpgsql immutable as $$
declare
  faltando text[];
begin
  select array_agg(c) into faltando
  from unnest(campos) as c
  where nullif(trim(coalesce(p ->> c, '')), '') is null;
  if faltando is not null then
    raise exception 'Campos obrigatórios ausentes: %.', array_to_string(faltando, ', ') using errcode = '22023';
  end if;
end $$;

create or replace function public._texto(p jsonb, campo text) returns text
language sql immutable as $$
  select coalesce(trim(p ->> campo), '')
$$;

create or replace function public._numero(v text, campo text) returns numeric
language plpgsql immutable as $$
begin
  if v is null or trim(v) = '' then return 0; end if;
  return round(trim(v)::numeric, 2);
exception when others then
  raise exception 'Valor inválido em "%": %.', campo, v using errcode = '22023';
end $$;

create or replace function public._data(v text, campo text) returns date
language plpgsql immutable as $$
begin
  if v is null or trim(v) = '' then return null; end if;
  if trim(v) !~ '^\d{4}-\d{2}-\d{2}$' then raise exception 'formato'; end if;
  return trim(v)::date;
exception when others then
  raise exception 'Data inválida em "%": %.', campo, v using errcode = '22023';
end $$;

-- Competência sempre como 'AAAA-MM' (aceita também 'AAAA-MM-DD')
create or replace function public._competencia(v text) returns text
language sql immutable as $$
  select case when trim(coalesce(v, '')) ~ '^\d{4}-\d{2}' then left(trim(v), 7) else '' end
$$;

-- ───────────────────────────── LEITURA ─────────────────────────────────────

-- Tudo o que as telas usam, no mesmo formato que o sistema já espera
create or replace function public.carregar_dados() returns json
language plpgsql stable security definer set search_path = public as $$
begin
  perform public._exigir_perfil(array['ADMIN', 'DIRETOR', 'FINANCEIRO']);
  return json_build_object(
    'contas', coalesce((
      select json_agg(json_build_object(
        'id', c.id::text, 'fornecedor', c.fornecedor, 'categoria', c.categoria,
        'solicitante', c.solicitante, 'descricao', c.descricao, 'valor', c.valor,
        'vencimento', to_char(c.vencimento, 'YYYY-MM-DD'), 'competencia', c.competencia,
        'dataPagamento', coalesce(to_char(c.data_pagamento, 'YYYY-MM-DD'), ''),
        'formaPagamento', c.forma_pagamento, 'jurosMulta', c.juros_multa,
        'numDocumento', c.num_documento, 'observacao', c.observacao,
        'usuario', c.usuario, 'dataRegistro', to_char(c.data_registro, 'YYYY-MM-DD')
      ) order by c.id) from public.contas c), '[]'::json),
    'fornecedores', coalesce((
      select json_agg(json_build_object(
        'id', f.id::text, 'nome', f.nome, 'tipo', f.tipo, 'documento', f.documento,
        'telefone', f.telefone, 'email', f.email, 'categoriaPadrao', f.categoria_padrao,
        'observacao', f.observacao, 'ativo', f.ativo
      ) order by f.id) from public.fornecedores f), '[]'::json),
    'categorias', coalesce((
      select json_agg(json_build_object(
        'id', k.id::text, 'nome', k.nome, 'tipo', k.tipo, 'frota', k.frota,
        'observacao', k.observacao, 'ativo', k.ativo
      ) order by k.id) from public.categorias k), '[]'::json),
    'solicitantes', coalesce((
      select json_agg(json_build_object(
        'id', s.id::text, 'nome', s.nome, 'departamento', s.departamento, 'cargo', s.cargo,
        'email', s.email, 'telefone', s.telefone, 'ativo', s.ativo
      ) order by s.id) from public.solicitantes s), '[]'::json)
  );
end $$;

create or replace function public.listar_usuarios() returns json
language plpgsql stable security definer set search_path = public as $$
begin
  perform public._exigir_perfil(array['ADMIN']);
  return coalesce((
    select json_agg(json_build_object(
      'id', u.id::text, 'nome', u.nome, 'email', u.email,
      'login', coalesce(u.login, ''), 'perfil', coalesce(u.perfil, ''), 'ativo', u.ativo
    ) order by u.nome) from public.usuarios u), '[]'::json);
end $$;

-- ───────────────────────────── CONTAS ──────────────────────────────────────

create or replace function public.criar_conta(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
declare
  v_id    bigint;
  v_chave text := nullif(public._texto(p, 'chaveEnvio'), '');
begin
  perform public._exigir_perfil(array['ADMIN', 'FINANCEIRO']);
  perform public._obrigatorio(p, array['fornecedor', 'categoria', 'descricao', 'valor', 'vencimento']);

  if v_chave is not null then
    select id into v_id from public.contas where chave_envio = v_chave;
    if found then return json_build_object('id', v_id::text, 'repetido', true); end if;
  end if;

  insert into public.contas (fornecedor, categoria, solicitante, descricao, valor, vencimento,
                             competencia, num_documento, observacao, usuario, chave_envio)
  values (public._texto(p, 'fornecedor'), public._texto(p, 'categoria'), public._texto(p, 'solicitante'),
          public._texto(p, 'descricao'), public._numero(p ->> 'valor', 'valor'),
          public._data(p ->> 'vencimento', 'vencimento'), public._competencia(p ->> 'competencia'),
          public._texto(p, 'numDocumento'), public._texto(p, 'observacao'), public.meu_login(), v_chave)
  returning id into v_id;

  return json_build_object('id', v_id::text);
exception when unique_violation then
  -- o mesmo envio chegou duas vezes ao mesmo tempo
  select id into v_id from public.contas where chave_envio = v_chave;
  return json_build_object('id', v_id::text, 'repetido', true);
end $$;

-- Todas as parcelas numa única transação: ou grava todas, ou nenhuma
create or replace function public.criar_conta_parcelada(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
declare
  v_chave  text := nullif(public._texto(p, 'chaveEnvio'), '');
  v_parc   jsonb;
  v_ids    json;
  v_total  int;
begin
  perform public._exigir_perfil(array['ADMIN', 'FINANCEIRO']);
  perform public._obrigatorio(p, array['fornecedor', 'categoria', 'descricao']);

  if jsonb_typeof(p -> 'parcelas') is distinct from 'array' or jsonb_array_length(p -> 'parcelas') < 2 then
    raise exception 'É necessário informar ao menos 2 parcelas.' using errcode = '22023';
  end if;

  for v_parc in select * from jsonb_array_elements(p -> 'parcelas') loop
    if public._numero(v_parc ->> 'valor', 'valor da parcela') <= 0
       or public._data(v_parc ->> 'vencimento', 'vencimento da parcela') is null then
      raise exception 'Cada parcela deve ter valor e vencimento.' using errcode = '22023';
    end if;
  end loop;

  if v_chave is not null and exists (select 1 from public.contas where chave_envio = v_chave || '#1') then
    select json_agg(id::text order by id), count(*) into v_ids, v_total
    from public.contas where starts_with(chave_envio, v_chave || '#');
    return json_build_object('ids', v_ids, 'total', v_total, 'repetido', true);
  end if;

  with inseridas as (
    insert into public.contas (fornecedor, categoria, solicitante, descricao, valor, vencimento,
                               competencia, num_documento, observacao, usuario, chave_envio)
    select public._texto(p, 'fornecedor'), public._texto(p, 'categoria'), public._texto(p, 'solicitante'),
           coalesce(nullif(public._texto(x, 'descricao'), ''), public._texto(p, 'descricao')),
           public._numero(x ->> 'valor', 'valor da parcela'), public._data(x ->> 'vencimento', 'vencimento da parcela'),
           public._competencia(p ->> 'competencia'), public._texto(p, 'numDocumento'),
           public._texto(p, 'observacao'), public.meu_login(),
           case when v_chave is null then null else v_chave || '#' || ord end
    from jsonb_array_elements(p -> 'parcelas') with ordinality as t (x, ord)
    order by ord
    returning id
  )
  select json_agg(id::text order by id), count(*) into v_ids, v_total from inseridas;

  return json_build_object('ids', v_ids, 'total', v_total);
end $$;

create or replace function public.atualizar_conta(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
declare
  v_perfil text;
  v_dono   text;
begin
  v_perfil := public._exigir_perfil(array['ADMIN', 'FINANCEIRO']);
  perform public._obrigatorio(p, array['id', 'fornecedor', 'categoria', 'descricao', 'valor', 'vencimento']);

  select usuario into v_dono from public.contas where id = (p ->> 'id')::bigint;
  if not found then raise exception 'Conta não encontrada.' using errcode = 'P0002'; end if;
  if v_perfil = 'FINANCEIRO' and v_dono is distinct from public.meu_login() then
    raise exception 'Você só pode editar contas lançadas por você.' using errcode = '42501';
  end if;

  -- Pagamento já registrado é preservado: editar a conta não mexe nele
  update public.contas set
    fornecedor    = public._texto(p, 'fornecedor'),
    categoria     = public._texto(p, 'categoria'),
    solicitante   = public._texto(p, 'solicitante'),
    descricao     = public._texto(p, 'descricao'),
    valor         = public._numero(p ->> 'valor', 'valor'),
    vencimento    = public._data(p ->> 'vencimento', 'vencimento'),
    competencia   = public._competencia(p ->> 'competencia'),
    num_documento = public._texto(p, 'numDocumento'),
    observacao    = public._texto(p, 'observacao')
  where id = (p ->> 'id')::bigint;

  return json_build_object('atualizado', true);
end $$;

create or replace function public.excluir_conta(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
begin
  perform public._exigir_perfil(array['ADMIN']);
  perform public._obrigatorio(p, array['id']);
  delete from public.contas where id = (p ->> 'id')::bigint;
  if not found then raise exception 'Conta não encontrada.' using errcode = 'P0002'; end if;
  return json_build_object('excluido', true);
end $$;

create or replace function public.registrar_pagamento(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
declare
  v_pago date;
begin
  perform public._exigir_perfil(array['ADMIN', 'FINANCEIRO']);
  perform public._obrigatorio(p, array['id', 'dataPagamento', 'formaPagamento']);

  select data_pagamento into v_pago from public.contas where id = (p ->> 'id')::bigint for update;
  if not found then raise exception 'Conta não encontrada.' using errcode = 'P0002'; end if;
  if v_pago is not null then
    raise exception 'Esta conta já possui pagamento registrado.' using errcode = '23505';
  end if;

  update public.contas set
    data_pagamento  = public._data(p ->> 'dataPagamento', 'data do pagamento'),
    forma_pagamento = public._texto(p, 'formaPagamento'),
    juros_multa     = public._numero(p ->> 'jurosMulta', 'juros/multa')
  where id = (p ->> 'id')::bigint;

  return json_build_object('registrado', true);
end $$;

-- ─────────────────────────── FORNECEDORES ──────────────────────────────────

create or replace function public.criar_fornecedor(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  perform public._exigir_perfil(array['ADMIN', 'FINANCEIRO']);
  perform public._obrigatorio(p, array['nome', 'tipo']);
  insert into public.fornecedores (nome, tipo, documento, telefone, email, categoria_padrao, observacao)
  values (public._texto(p, 'nome'), public._texto(p, 'tipo'), public._texto(p, 'documento'),
          public._texto(p, 'telefone'), public._texto(p, 'email'), public._texto(p, 'categoriaPadrao'),
          public._texto(p, 'observacao'))
  returning id into v_id;
  return json_build_object('id', v_id::text);
end $$;

create or replace function public.atualizar_fornecedor(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
begin
  perform public._exigir_perfil(array['ADMIN', 'FINANCEIRO']);
  perform public._obrigatorio(p, array['id', 'nome', 'tipo']);
  update public.fornecedores set
    nome = public._texto(p, 'nome'), tipo = public._texto(p, 'tipo'), documento = public._texto(p, 'documento'),
    telefone = public._texto(p, 'telefone'), email = public._texto(p, 'email'),
    categoria_padrao = public._texto(p, 'categoriaPadrao'), observacao = public._texto(p, 'observacao')
  where id = (p ->> 'id')::bigint;
  if not found then raise exception 'Fornecedor não encontrado.' using errcode = 'P0002'; end if;
  return json_build_object('atualizado', true);
end $$;

create or replace function public.toggle_fornecedor(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
begin
  perform public._exigir_perfil(array['ADMIN']);
  perform public._obrigatorio(p, array['id', 'ativo']);
  update public.fornecedores set ativo = (p ->> 'ativo')::boolean where id = (p ->> 'id')::bigint;
  if not found then raise exception 'Fornecedor não encontrado.' using errcode = 'P0002'; end if;
  return json_build_object('ativo', (p ->> 'ativo')::boolean);
end $$;

-- ──────────────────────────── CATEGORIAS ───────────────────────────────────

create or replace function public.criar_categoria(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  perform public._exigir_perfil(array['ADMIN', 'FINANCEIRO']);
  perform public._obrigatorio(p, array['nome', 'tipo']);
  insert into public.categorias (nome, tipo, frota, observacao)
  values (public._texto(p, 'nome'), public._texto(p, 'tipo'), coalesce((p ->> 'frota')::boolean, false),
          public._texto(p, 'observacao'))
  returning id into v_id;
  return json_build_object('id', v_id::text);
end $$;

create or replace function public.atualizar_categoria(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
begin
  perform public._exigir_perfil(array['ADMIN', 'FINANCEIRO']);
  perform public._obrigatorio(p, array['id', 'nome', 'tipo']);
  update public.categorias set
    nome = public._texto(p, 'nome'), tipo = public._texto(p, 'tipo'),
    frota = coalesce((p ->> 'frota')::boolean, false), observacao = public._texto(p, 'observacao')
  where id = (p ->> 'id')::bigint;
  if not found then raise exception 'Categoria não encontrada.' using errcode = 'P0002'; end if;
  return json_build_object('atualizado', true);
end $$;

create or replace function public.toggle_categoria(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
begin
  perform public._exigir_perfil(array['ADMIN']);
  perform public._obrigatorio(p, array['id', 'ativo']);
  update public.categorias set ativo = (p ->> 'ativo')::boolean where id = (p ->> 'id')::bigint;
  if not found then raise exception 'Categoria não encontrada.' using errcode = 'P0002'; end if;
  return json_build_object('ativo', (p ->> 'ativo')::boolean);
end $$;

-- ─────────────────────────── SOLICITANTES ──────────────────────────────────

create or replace function public.criar_solicitante(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  perform public._exigir_perfil(array['ADMIN', 'FINANCEIRO']);
  perform public._obrigatorio(p, array['nome']);
  insert into public.solicitantes (nome, departamento, cargo, email, telefone)
  values (public._texto(p, 'nome'), public._texto(p, 'departamento'), public._texto(p, 'cargo'),
          public._texto(p, 'email'), public._texto(p, 'telefone'))
  returning id into v_id;
  return json_build_object('id', v_id::text);
end $$;

create or replace function public.atualizar_solicitante(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
begin
  perform public._exigir_perfil(array['ADMIN', 'FINANCEIRO']);
  perform public._obrigatorio(p, array['id', 'nome']);
  update public.solicitantes set
    nome = public._texto(p, 'nome'), departamento = public._texto(p, 'departamento'),
    cargo = public._texto(p, 'cargo'), email = public._texto(p, 'email'), telefone = public._texto(p, 'telefone')
  where id = (p ->> 'id')::bigint;
  if not found then raise exception 'Solicitante não encontrado.' using errcode = 'P0002'; end if;
  return json_build_object('atualizado', true);
end $$;

create or replace function public.toggle_solicitante(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
begin
  perform public._exigir_perfil(array['ADMIN']);
  perform public._obrigatorio(p, array['id', 'ativo']);
  update public.solicitantes set ativo = (p ->> 'ativo')::boolean where id = (p ->> 'id')::bigint;
  if not found then raise exception 'Solicitante não encontrado.' using errcode = 'P0002'; end if;
  return json_build_object('ativo', (p ->> 'ativo')::boolean);
end $$;

-- ───────────────────────────── USUÁRIOS ────────────────────────────────────
-- O login (e-mail e senha) é criado no painel do Supabase (Authentication → Add user).
-- Aqui o ADMIN define nome, login curto, perfil e se está ativo.

create or replace function public.atualizar_usuario(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
declare
  v_login text := lower(public._texto(p, 'login'));
begin
  perform public._exigir_perfil(array['ADMIN']);
  perform public._obrigatorio(p, array['id', 'nome', 'login', 'perfil']);
  if public._texto(p, 'perfil') not in ('ADMIN', 'DIRETOR', 'FINANCEIRO') then
    raise exception 'Perfil inválido: %.', public._texto(p, 'perfil') using errcode = '22023';
  end if;
  if exists (select 1 from public.usuarios where lower(login) = v_login and id <> (p ->> 'id')::uuid) then
    raise exception 'Login "%" já está em uso por outro usuário.', v_login using errcode = '23505';
  end if;
  update public.usuarios set nome = public._texto(p, 'nome'), login = v_login, perfil = public._texto(p, 'perfil')
  where id = (p ->> 'id')::uuid;
  if not found then raise exception 'Usuário não encontrado.' using errcode = 'P0002'; end if;
  return json_build_object('atualizado', true);
end $$;

create or replace function public.toggle_usuario(p jsonb) returns json
language plpgsql security definer set search_path = public as $$
begin
  perform public._exigir_perfil(array['ADMIN']);
  perform public._obrigatorio(p, array['id', 'ativo']);
  if (p ->> 'id')::uuid = auth.uid() and not (p ->> 'ativo')::boolean then
    raise exception 'Você não pode desativar o seu próprio usuário.' using errcode = '42501';
  end if;
  if (p ->> 'ativo')::boolean
     and (select perfil from public.usuarios where id = (p ->> 'id')::uuid) is null then
    raise exception 'Defina o perfil do usuário antes de ativá-lo.' using errcode = '22023';
  end if;
  update public.usuarios set ativo = (p ->> 'ativo')::boolean where id = (p ->> 'id')::uuid;
  if not found then raise exception 'Usuário não encontrado.' using errcode = 'P0002'; end if;
  return json_build_object('ativo', (p ->> 'ativo')::boolean);
end $$;

-- Todo login criado no painel ganha um perfil vazio e inativo, esperando o ADMIN
create or replace function public.novo_usuario_auth() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.usuarios (id, email, nome)
  values (new.id, new.email, split_part(new.email, '@', 1))
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists ao_criar_usuario on auth.users;
create trigger ao_criar_usuario
  after insert on auth.users
  for each row execute function public.novo_usuario_auth();

-- Logins criados antes deste script
insert into public.usuarios (id, email, nome)
select id, email, split_part(email, '@', 1) from auth.users
on conflict (id) do nothing;

-- ───────────────────────── REGRAS DE ACESSO (RLS) ──────────────────────────

alter table public.usuarios     enable row level security;
alter table public.fornecedores enable row level security;
alter table public.categorias   enable row level security;
alter table public.solicitantes enable row level security;
alter table public.contas       enable row level security;

-- Ninguém grava direto: só leitura, e só pelas regras abaixo
revoke all on public.usuarios, public.fornecedores, public.categorias, public.solicitantes, public.contas
  from anon, authenticated;
grant select on public.usuarios, public.fornecedores, public.categorias, public.solicitantes, public.contas
  to authenticated;

drop policy if exists leitura on public.fornecedores;
create policy leitura on public.fornecedores for select to authenticated using (public.meu_perfil() is not null);
drop policy if exists leitura on public.categorias;
create policy leitura on public.categorias for select to authenticated using (public.meu_perfil() is not null);
drop policy if exists leitura on public.solicitantes;
create policy leitura on public.solicitantes for select to authenticated using (public.meu_perfil() is not null);
drop policy if exists leitura on public.contas;
create policy leitura on public.contas for select to authenticated using (public.meu_perfil() is not null);
drop policy if exists leitura on public.usuarios;
create policy leitura on public.usuarios for select to authenticated
  using (id = auth.uid() or public.meu_perfil() = 'ADMIN');

-- Funções: ninguém de fora; logados só as do sistema (as auxiliares ficam internas)
revoke execute on all functions in schema public from public, anon, authenticated;
grant execute on function
  public.meu_perfil(), public.meu_login(), public.meu_usuario(),
  public.carregar_dados(), public.listar_usuarios(),
  public.criar_conta(jsonb), public.criar_conta_parcelada(jsonb), public.atualizar_conta(jsonb),
  public.excluir_conta(jsonb), public.registrar_pagamento(jsonb),
  public.criar_fornecedor(jsonb), public.atualizar_fornecedor(jsonb), public.toggle_fornecedor(jsonb),
  public.criar_categoria(jsonb), public.atualizar_categoria(jsonb), public.toggle_categoria(jsonb),
  public.criar_solicitante(jsonb), public.atualizar_solicitante(jsonb), public.toggle_solicitante(jsonb),
  public.atualizar_usuario(jsonb), public.toggle_usuario(jsonb)
to authenticated;
